### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by jayblu** [Favna/SEEDChecker#2]
So, after adjusting some speeds and such (just to test, ya know) and saving my new script, it won't compile. It comes out with `Error: Could not find or load main class SeedCheckerLauncher`

I don't really know how to fix this. I already reinstalled Java.

**Comment by favna** [comment]
This is partially related to not having JDK in PATH which can be added by writing this in command prompt:
`set PATH=%PATH%;C:\Path\To\jdk1.8.X_XX\bin`. Generally `C:\Program Files\Java\jdk1.8.0_91\bin`.

However I will have to look into it more once I'm home because this currently still throws an error saying it cannot find the other classes which I only have locally.
